-- ============================================================
-- Movie-Mate Database Schema (with Auth)
-- MySQL 8.x
-- ============================================================

DROP DATABASE IF EXISTS movie_mate;
CREATE DATABASE movie_mate CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE movie_mate;

-- ------------------------------------------------------------
-- Table: users  (includes password hash + role)
-- ------------------------------------------------------------
CREATE TABLE users (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    email      VARCHAR(120) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       ENUM('user','admin') NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_users_username (username)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Table: movies
-- ------------------------------------------------------------
CREATE TABLE movies (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    description  TEXT,
    genre        VARCHAR(100) NOT NULL,
    release_year INT          NOT NULL,
    director     VARCHAR(150),
    cast_list    TEXT,
    poster_url   VARCHAR(500),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_movies_title (title),
    INDEX idx_movies_genre (genre),
    INDEX idx_movies_release_year (release_year)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Table: ratings
-- ------------------------------------------------------------
CREATE TABLE ratings (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    user_id    INT     NOT NULL,
    movie_id   INT     NOT NULL,
    rating     TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ratings_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    CONSTRAINT fk_ratings_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    CONSTRAINT uq_rating_user_movie UNIQUE (user_id, movie_id),
    INDEX idx_ratings_movie (movie_id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Table: reviews
-- ------------------------------------------------------------
CREATE TABLE reviews (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    user_id     INT     NOT NULL,
    movie_id    INT     NOT NULL,
    review_text TEXT    NOT NULL,
    rating      TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
    CONSTRAINT fk_reviews_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    INDEX idx_reviews_movie (movie_id)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Seed: Admin and demo users
-- Passwords are bcrypt hashes — DO NOT edit manually.
-- admin123  -> for admin account
-- user123   -> for demo user accounts
-- Run backend/seed_users.py to regenerate with correct hashes.
-- ------------------------------------------------------------
-- (Users are inserted by seed_users.py after Flask starts — 
--  bcrypt hashes must be generated by Python, not SQL)

-- ------------------------------------------------------------
-- Seed: Movies
-- ------------------------------------------------------------
INSERT INTO movies (title, description, genre, release_year, director, cast_list, poster_url) VALUES
('Inception',           'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',      'Sci-Fi',  2010, 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',    'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg'),
('The Dark Knight',     'When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability.',        'Action',  2008, 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart',              'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'),
('Parasite',            'Greed and class discrimination threaten the relationship between the wealthy Park family and the destitute Kim clan.',     'Drama',   2019, 'Bong Joon-ho',     'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',               'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'),
('Interstellar',        'A team of explorers travel through a wormhole in space to ensure humanity survival.',                                      'Sci-Fi',  2014, 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',     'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'),
('The Grand Budapest Hotel','The adventures of Gustave H, a legendary concierge, and Zero Moustafa, the lobby boy who becomes his trusted friend.','Comedy', 2014, 'Wes Anderson',      'Ralph Fiennes, Tony Revolori, Saoirse Ronan',             'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg'),
('Whiplash',            'A promising young drummer enrolls at a cutthroat music conservatory where his instructor will stop at nothing.',           'Drama',   2014, 'Damien Chazelle',  'Miles Teller, J.K. Simmons, Melissa Benoist',             'https://image.tmdb.org/t/p/w500/oPxnRhyAIzJKGUEuq3cxL9Mfo1z.jpg');
